# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wserver.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(400, 232)
        self.layoutWidget = QtWidgets.QWidget(Server)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 213))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.name = QtWidgets.QLineEdit(self.layoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.boundaries = QtWidgets.QComboBox(self.layoutWidget)
        self.boundaries.setObjectName("boundaries")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.boundaries)
        self.label3 = QtWidgets.QLabel(self.layoutWidget)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.OS = QtWidgets.QComboBox(self.layoutWidget)
        self.OS.setObjectName("OS")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.OS.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.OS)
        self.label4 = QtWidgets.QLabel(self.layoutWidget)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.isHardened = QtWidgets.QComboBox(self.layoutWidget)
        self.isHardened.setObjectName("isHardened")
        self.isHardened.addItem("")
        self.isHardened.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.isHardened)
        self.label5 = QtWidgets.QLabel(self.layoutWidget)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.sanitizesInput = QtWidgets.QComboBox(self.layoutWidget)
        self.sanitizesInput.setObjectName("sanitizesInput")
        self.sanitizesInput.addItem("")
        self.sanitizesInput.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sanitizesInput)
        self.label6 = QtWidgets.QLabel(self.layoutWidget)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.encodesOutput = QtWidgets.QComboBox(self.layoutWidget)
        self.encodesOutput.setObjectName("encodesOutput")
        self.encodesOutput.addItem("")
        self.encodesOutput.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.encodesOutput)
        self.label7 = QtWidgets.QLabel(self.layoutWidget)
        self.label7.setObjectName("label7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label7)
        self.authorizesSource = QtWidgets.QComboBox(self.layoutWidget)
        self.authorizesSource.setObjectName("authorizesSource")
        self.authorizesSource.addItem("")
        self.authorizesSource.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.authorizesSource)

        self.retranslateUi(Server)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "Form"))
        self.label1.setText(_translate("Server", "Name"))
        self.label2.setText(_translate("Server", "inBoundary"))
        self.label3.setText(_translate("Server", "OS"))
        self.OS.setItemText(0, _translate("Server", "Windows 10"))
        self.OS.setItemText(1, _translate("Server", "Windows 8"))
        self.OS.setItemText(2, _translate("Server", "Windows 7"))
        self.OS.setItemText(3, _translate("Server", "macOS"))
        self.OS.setItemText(4, _translate("Server", "Ubuntu"))
        self.OS.setItemText(5, _translate("Server", "CentOS"))
        self.OS.setItemText(6, _translate("Server", "Fedora"))
        self.OS.setItemText(7, _translate("Server", "Red Hat Linux"))
        self.OS.setItemText(8, _translate("Server", "Apple iOS"))
        self.OS.setItemText(9, _translate("Server", "Android"))
        self.label4.setText(_translate("Server", "isHardened"))
        self.isHardened.setItemText(0, _translate("Server", "True"))
        self.isHardened.setItemText(1, _translate("Server", "False"))
        self.label5.setText(_translate("Server", "sanitizesInput"))
        self.sanitizesInput.setItemText(0, _translate("Server", "True"))
        self.sanitizesInput.setItemText(1, _translate("Server", "False"))
        self.label6.setText(_translate("Server", "encodesOutput"))
        self.encodesOutput.setItemText(0, _translate("Server", "True"))
        self.encodesOutput.setItemText(1, _translate("Server", "False"))
        self.label7.setText(_translate("Server", "authorizesSources"))
        self.authorizesSource.setItemText(0, _translate("Server", "True"))
        self.authorizesSource.setItemText(1, _translate("Server", "False"))

